#!/bin/bash
# Author: Joshua Hoskins (jhoskins@jlab.org) 
# 08-07-2012


slug_num=$1

DST="/u/home/jhoskins/QwAnalysis_trunk/Extensions/Regression/QwBeamModulation/Slug"
DST_Dbug="/u/home/jhoskins/QwBeamModulation/slug"

argument="MakeSlug.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass5_unreg_mps.txt\",\"${DST}/slug${slug_num}.root\")"

root -n -q -b -l ${argument} #>${DST_Dbug}/slug${slug_num}.out



