#!/bin/bash
# Author: Joshua Hoskins (jhoskins@jlab.org) 
# 08-07-2012

run=$1
runlet=$2

scriptPath=`dirname $0`

qwstem="QwPass5b"

if [ -z $run ]; then
    echo "Must specify run number."
    exit
fi

if [ -z $runlet ]; then
    echo "Must specify runlet range. Example: 0:4"
    exit
fi

if [ $runlet == "-1" ]; then
    echo "Runlet set to full."
    range="full"
else
    range=$runlet
fi


#export QW_ROOTFILES=/volatile/hallc/qweak/QwAnalysis/run1/rootfiles

DST="/work/hallc/qweak/QwAnalysis/run1/pass5b_bmod_regression/mps_slug"
LIST="/group/qweak/QwAnalysis/Linux/QwAnalysis_3.04/Extensions/Macros/Parity/SlugPlots/run1pass5b/"
DST_Dbug="/work/hallc/qweak/QwAnalysis/run1/pass5b_bmod_regression/mps_slug/out_files"

argument="${scriptPath}/MakeSlugMPS.C+(${run},\"${runlet}\",\"${scriptPath}/leaflist_run1pass5_unreg_mps.txt\",\"${DST}/mps_only_${run}_${range}.root\",\"${qwstem}\")"

echo "root -n -q -b -l ${argument}"

root -n -q -l -b ${argument} > ${DST_Dbug}/run_makeslug_mps_${run}_${range}.out



