#!/bin/csh
#

set orig_dir = `pwd`

cd `dirname $0`
set local_path = `pwd`

setenv QWANALYSIS `echo $local_path | sed 's/\/SetupFiles//'`

cat >! SET_ME_UP.csh << END
#!/bin/csh
#
set analyzer_version = $QWANALYSIS

###
###  DO NOT CHANGE THE COMMANDS BELOW!!!
###
	setenv QWANALYSIS \$analyzer_version
	unsetenv RCLD_LIBRARY_PATH
	unsetenv RCQWANALYSIS
	unsetenv RCQWANALYSIS_INIT

	source \${QWANALYSIS}/SetupFiles/.QwSetup.csh

unset analyzer_version

END
