/********************************************************************
* QwGUIComboBoxDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIComboBoxDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIComboBoxDict();
extern void G__cpp_setup_inheritanceQwGUIComboBoxDict();
extern void G__cpp_setup_typetableQwGUIComboBoxDict();
extern void G__cpp_setup_memvarQwGUIComboBoxDict();
extern void G__cpp_setup_globalQwGUIComboBoxDict();
extern void G__cpp_setup_memfuncQwGUIComboBoxDict();
extern void G__cpp_setup_funcQwGUIComboBoxDict();
extern void G__set_cpp_environmentQwGUIComboBoxDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIComboBox.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIComboBoxDictLN_TClass;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TObject;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TGObject;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TQObject;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TGWidget;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_TGComboBox;
extern G__linked_taginfo G__QwGUIComboBoxDictLN_QwGUIComboBox;

/* STUB derived class for protected member access */
