/********************************************************************
* QwGUISuperCanvasDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUISuperCanvasDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUISuperCanvasDict();
extern void G__cpp_setup_inheritanceQwGUISuperCanvasDict();
extern void G__cpp_setup_typetableQwGUISuperCanvasDict();
extern void G__cpp_setup_memvarQwGUISuperCanvasDict();
extern void G__cpp_setup_globalQwGUISuperCanvasDict();
extern void G__cpp_setup_memfuncQwGUISuperCanvasDict();
extern void G__cpp_setup_funcQwGUISuperCanvasDict();
extern void G__set_cpp_environmentQwGUISuperCanvasDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUISuperCanvas.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TClass;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TBuffer;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TObject;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TCanvas;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TStyle;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TVirtualPad;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TQObject;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TAttLine;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TAttFill;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TAttPad;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_EEventType;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TPad;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_maplEQwcLcLEQwColorcOstringcOlesslEQwcLcLEQwColorgRcOallocatorlEpairlEconstsPQwcLcLEQwColorcOstringgRsPgRsPgR;
extern G__linked_taginfo G__QwGUISuperCanvasDictLN_QwGUISuperCanvas;

/* STUB derived class for protected member access */
