/********************************************************************
* QwGUIDatabaseContainerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIDatabaseContainerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIDatabaseContainerDict();
extern void G__cpp_setup_inheritanceQwGUIDatabaseContainerDict();
extern void G__cpp_setup_typetableQwGUIDatabaseContainerDict();
extern void G__cpp_setup_memvarQwGUIDatabaseContainerDict();
extern void G__cpp_setup_globalQwGUIDatabaseContainerDict();
extern void G__cpp_setup_memfuncQwGUIDatabaseContainerDict();
extern void G__cpp_setup_funcQwGUIDatabaseContainerDict();
extern void G__set_cpp_environmentQwGUIDatabaseContainerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIDatabaseContainer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TClass;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TQObject;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_ERFileTypes;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_ERFileModes;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_RDataContainer;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_QwDatabase;
extern G__linked_taginfo G__QwGUIDatabaseContainerDictLN_QwGUIDatabaseContainer;

/* STUB derived class for protected member access */
