/********************************************************************
* QwGUIProgressDialogDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIProgressDialogDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIProgressDialogDict();
extern void G__cpp_setup_inheritanceQwGUIProgressDialogDict();
extern void G__cpp_setup_typetableQwGUIProgressDialogDict();
extern void G__cpp_setup_memvarQwGUIProgressDialogDict();
extern void G__cpp_setup_globalQwGUIProgressDialogDict();
extern void G__cpp_setup_memfuncQwGUIProgressDialogDict();
extern void G__cpp_setup_funcQwGUIProgressDialogDict();
extern void G__set_cpp_environmentQwGUIProgressDialogDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIProgressDialog.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TClass;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TObject;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TQObject;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGObject;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGLayoutHints;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGTextButton;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGVerticalFrame;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGMainFrame;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGTransientFrame;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_TGHProgressBar;
extern G__linked_taginfo G__QwGUIProgressDialogDictLN_QwGUIProgressDialog;

/* STUB derived class for protected member access */
