/********************************************************************
* QwGUIDatabaseDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIDatabaseDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIDatabaseDict();
extern void G__cpp_setup_inheritanceQwGUIDatabaseDict();
extern void G__cpp_setup_typetableQwGUIDatabaseDict();
extern void G__cpp_setup_memvarQwGUIDatabaseDict();
extern void G__cpp_setup_globalQwGUIDatabaseDict();
extern void G__cpp_setup_memfuncQwGUIDatabaseDict();
extern void G__cpp_setup_funcQwGUIDatabaseDict();
extern void G__set_cpp_environmentQwGUIDatabaseDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIDatabase.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIDatabaseDictLN_TClass;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TObject;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TObjArray;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TString;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TPaveText;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGObject;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TQObject;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGLayoutHints;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGTextButton;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGVerticalFrame;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGTab;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TH1;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_RDataContainer;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGLabel;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGNumberEntry;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_TGComboBox;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_maplEQwcLcLEQwColorcOstringcOlesslEQwcLcLEQwColorgRcOallocatorlEpairlEconstsPQwcLcLEQwColorcOstringgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_QwGUISubSystem;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_QwGUIGoodForSettings;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseDictLN_QwGUIDatabase;

/* STUB derived class for protected member access */
