/********************************************************************
* QwGUISubSystemDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUISubSystemDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUISubSystemDict();
extern void G__cpp_setup_inheritanceQwGUISubSystemDict();
extern void G__cpp_setup_typetableQwGUISubSystemDict();
extern void G__cpp_setup_memvarQwGUISubSystemDict();
extern void G__cpp_setup_globalQwGUISubSystemDict();
extern void G__cpp_setup_memfuncQwGUISubSystemDict();
extern void G__cpp_setup_funcQwGUISubSystemDict();
extern void G__set_cpp_environmentQwGUISubSystemDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUISubSystem.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUISubSystemDictLN_TClass;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TBuffer;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TObject;
extern G__linked_taginfo G__QwGUISubSystemDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TString;
extern G__linked_taginfo G__QwGUISubSystemDictLN_RUNTYPE;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TGObject;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TQObject;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TGWindow;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TGFrame;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUISubSystemDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_RDataContainer;
extern G__linked_taginfo G__QwGUISubSystemDictLN_QwGUIProgressDialog;
extern G__linked_taginfo G__QwGUISubSystemDictLN_QwGUIDatabaseContainer;
extern G__linked_taginfo G__QwGUISubSystemDictLN_maplEQwcLcLEQwColorcOstringcOlesslEQwcLcLEQwColorgRcOallocatorlEpairlEconstsPQwcLcLEQwColorcOstringgRsPgRsPgR;
extern G__linked_taginfo G__QwGUISubSystemDictLN_QwGUISubSystem;

/* STUB derived class for protected member access */
