/********************************************************************
* QwGUIPlotOptionsDialogDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIPlotOptionsDialogDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIPlotOptionsDialogDict();
extern void G__cpp_setup_inheritanceQwGUIPlotOptionsDialogDict();
extern void G__cpp_setup_typetableQwGUIPlotOptionsDialogDict();
extern void G__cpp_setup_memvarQwGUIPlotOptionsDialogDict();
extern void G__cpp_setup_globalQwGUIPlotOptionsDialogDict();
extern void G__cpp_setup_memfuncQwGUIPlotOptionsDialogDict();
extern void G__cpp_setup_funcQwGUIPlotOptionsDialogDict();
extern void G__set_cpp_environmentQwGUIPlotOptionsDialogDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIPlotOptionsDialog.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TClass;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TObject;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TQObject;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGObject;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGLayoutHints;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGMainFrame;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGTransientFrame;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGGroupFrame;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGLabel;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGButton;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGCheckButton;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TGNumberEntry;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_DataOptions;
extern G__linked_taginfo G__QwGUIPlotOptionsDialogDictLN_QwGUIPlotOptionsDialog;

/* STUB derived class for protected member access */
