/********************************************************************
* QwGUIDatabaseSelectionDialogDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIDatabaseSelectionDialogDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIDatabaseSelectionDialogDict();
extern void G__cpp_setup_inheritanceQwGUIDatabaseSelectionDialogDict();
extern void G__cpp_setup_typetableQwGUIDatabaseSelectionDialogDict();
extern void G__cpp_setup_memvarQwGUIDatabaseSelectionDialogDict();
extern void G__cpp_setup_globalQwGUIDatabaseSelectionDialogDict();
extern void G__cpp_setup_memfuncQwGUIDatabaseSelectionDialogDict();
extern void G__cpp_setup_funcQwGUIDatabaseSelectionDialogDict();
extern void G__set_cpp_environmentQwGUIDatabaseSelectionDialogDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIDatabaseSelectionDialog.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TClass;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TObject;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TString;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TQObject;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGObject;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGLayoutHints;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGTextButton;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGVerticalFrame;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGMainFrame;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGTransientFrame;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGLabel;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGCheckButton;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGTextBuffer;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGTextEntry;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TGNumberEntry;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_DatabaseOptions;
extern G__linked_taginfo G__QwGUIDatabaseSelectionDialogDictLN_QwGUIDatabaseSelectionDialog;

/* STUB derived class for protected member access */
