/********************************************************************
* QwGUIDataWindowDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIDataWindowDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIDataWindowDict();
extern void G__cpp_setup_inheritanceQwGUIDataWindowDict();
extern void G__cpp_setup_typetableQwGUIDataWindowDict();
extern void G__cpp_setup_memvarQwGUIDataWindowDict();
extern void G__cpp_setup_globalQwGUIDataWindowDict();
extern void G__cpp_setup_memfuncQwGUIDataWindowDict();
extern void G__cpp_setup_funcQwGUIDataWindowDict();
extern void G__set_cpp_environmentQwGUIDataWindowDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIDataWindow.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIDataWindowDictLN_TClass;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TObject;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TQObject;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TGObject;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TGMainFrame;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TGTransientFrame;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_ERPlotTypes;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_RSDataWindow;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_ENDataType;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_DataOptions;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_QwGUIPlotOptionsDialog;
extern G__linked_taginfo G__QwGUIDataWindowDictLN_QwGUIDataWindow;

/* STUB derived class for protected member access */
