/********************************************************************
* QwGUIMainDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QwGUIMainDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQwGUIMainDict();
extern void G__cpp_setup_inheritanceQwGUIMainDict();
extern void G__cpp_setup_typetableQwGUIMainDict();
extern void G__cpp_setup_memvarQwGUIMainDict();
extern void G__cpp_setup_globalQwGUIMainDict();
extern void G__cpp_setup_memfuncQwGUIMainDict();
extern void G__cpp_setup_funcQwGUIMainDict();
extern void G__set_cpp_environmentQwGUIMainDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/QwGUIMain.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QwGUIMainDictLN_TClass;
extern G__linked_taginfo G__QwGUIMainDictLN_TBuffer;
extern G__linked_taginfo G__QwGUIMainDictLN_TMemberInspector;
extern G__linked_taginfo G__QwGUIMainDictLN_TObject;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIMainDictLN_TList;
extern G__linked_taginfo G__QwGUIMainDictLN_TObjArray;
extern G__linked_taginfo G__QwGUIMainDictLN_TString;
extern G__linked_taginfo G__QwGUIMainDictLN_Event_t;
extern G__linked_taginfo G__QwGUIMainDictLN_TGObject;
extern G__linked_taginfo G__QwGUIMainDictLN_TQObject;
extern G__linked_taginfo G__QwGUIMainDictLN_TQObjSender;
extern G__linked_taginfo G__QwGUIMainDictLN_TGWindow;
extern G__linked_taginfo G__QwGUIMainDictLN_TGFrame;
extern G__linked_taginfo G__QwGUIMainDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QwGUIMainDictLN_TGLayoutHints;
extern G__linked_taginfo G__QwGUIMainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QwGUIMainDictLN_TGVerticalFrame;
extern G__linked_taginfo G__QwGUIMainDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__QwGUIMainDictLN_TGMainFrame;
extern G__linked_taginfo G__QwGUIMainDictLN_TGTab;
extern G__linked_taginfo G__QwGUIMainDictLN_TCanvas;
extern G__linked_taginfo G__QwGUIMainDictLN_TGPopupMenu;
extern G__linked_taginfo G__QwGUIMainDictLN_TGCheckButton;
extern G__linked_taginfo G__QwGUIMainDictLN_TGTextEntry;
extern G__linked_taginfo G__QwGUIMainDictLN_QwGUIComboBox;
extern G__linked_taginfo G__QwGUIMainDictLN_TGTextBuffer;
extern G__linked_taginfo G__QwGUIMainDictLN_TGNumberEntry;
extern G__linked_taginfo G__QwGUIMainDictLN_TGLabel;
extern G__linked_taginfo G__QwGUIMainDictLN_TGMenuBar;
extern G__linked_taginfo G__QwGUIMainDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__QwGUIMainDictLN_TGText;
extern G__linked_taginfo G__QwGUIMainDictLN_TGTextEdit;
extern G__linked_taginfo G__QwGUIMainDictLN_TGHorizontal3DLine;
extern G__linked_taginfo G__QwGUIMainDictLN_ERFileStatus;
extern G__linked_taginfo G__QwGUIMainDictLN_ClineArgs;
extern G__linked_taginfo G__QwGUIMainDictLN_QwGUIHelpBrowser;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIMainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QwGUIMainDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QwGUIMainDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__QwGUIMainDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__QwGUIMainDictLN_RDataContainer;
extern G__linked_taginfo G__QwGUIMainDictLN_TPad;
extern G__linked_taginfo G__QwGUIMainDictLN_QwGUIDatabaseContainer;
extern G__linked_taginfo G__QwGUIMainDictLN_RUNTYPE;
extern G__linked_taginfo G__QwGUIMainDictLN_maplEQwcLcLEQwColorcOstringcOlesslEQwcLcLEQwColorgRcOallocatorlEpairlEconstsPQwcLcLEQwColorcOstringgRsPgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_QwGUISubSystem;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIMainDictLN_QwGUIDatabase;
extern G__linked_taginfo G__QwGUIMainDictLN_QwGUIMain;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QwGUIMainDictLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR;
extern G__linked_taginfo G__QwGUIMainDictLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
