#!/bin/bash
# Author : Rakitha Beminiwattha
# 02/20/2011
# This bash script allows us to set the norminal values for the PC hardware counts
# To use it,
# compile using 
# chmod +x FlipPCValues
# and then run ./FlipPCValues
# EPICS names PC [+] C1068_QDAC01PC [-] C1068_QDAC02

#PITA starting setpoints when IHWP is flipped from the last OUT-IN
# flip done on 02-02-2011 at ~3.00pm- Rakitha 02/03/2011
PC_pos_t0_IN=43600
PC_neg_t0_IN=40600
PC_pos_t0_OUT=42900
PC_neg_t0_OUT=41300

PC_pos_current="`caget -t C1068_QDAC01`"
PC_neg_current="`caget -t C1068_QDAC02`"


IHWP_State="`caget -t IGL1I00DI24_24M`"
#IHWP_State="IN"
echo "Setting Pockels Cell values "

if [ "$IHWP_State" == "OUT " ];then
    	echo "Current IHWP state is OUT"
	echo "Norminal PC_pos = $PC_pos_t0_OUT"
	echo "Current PC_pos = $PC_pos_current"
	echo "Norminal PC_neg = $PC_neg_t0_OUT"
	echo "Current PC_pos = $PC_neg_current"
	echo "Setting norminal values"
	caput C1068_QDAC01 $PC_pos_t0_OUT
	caput C1068_QDAC02 $PC_neg_t0_OUT
else
    	echo "Current IHWP state is IN"	
	echo "Norminal PC_pos = $PC_pos_t0_IN"
	echo "Current PC_pos = $PC_pos_current"
	echo "Norminal PC_neg = $PC_neg_t0_IN"
	echo "Current PC_pos = $PC_neg_current"
	echo "Setting norminal values"
	caput C1068_QDAC01 $PC_pos_t0_IN
	caput C1068_QDAC02 $PC_neg_t0_IN
fi


