#!/bin/bash

folder=$1

SRC="/volatile/hallc/qweak/QwAnalysis/run1/pass4regression/${folder}"
#DEST="/data/disk1/leacock/slugplots/25percent/lrb_links/${folder}"
DEST="/volatile/hallc/qweak/leacock/25percent/lrb_links/${folder}"

#rm -f ${DEST}/${folder}/*

arr=( $(find ${SRC} -type f -name reg_temp\*.root) )
#echo ${#arr[@]}
#echo ${arr[@]}

for d in "${arr[@]}"; do
  #echo ${d}
  /bin/cp -s -u -v ${d} ${DEST}/  >/dev/null 2>&1
done

