SUBDIRS = QwGUILib QwGUIView QwAutoGUIView QwDataBaseGUIView QwRealTimeGUIView
DATA_SUBDIRS = 
CONFFILES = 

.PHONY : $(SUBDIRS) clean VERSION

all: QwGUIData $(DATA_SUBDIRS) $(CONFFILES)

QwGUILib  : VERSION
QwGUIView : VERSION QwGUILib
QwAutoGUIView : VERSION
QwRealTimeGUIView : VERSION QwGUILib
QwGUIData : QwGUIView QwAutoGUIView QwDataBaseGUIView QwRealTimeGUIView
#QwGUIData : QwGUIView
$(SUBDIRS) : 
	$(MAKE) -C $@

#
# write to VERSION for permanent record
# VERS = has "-$USER" appended if any files have changed
#  in this case the status is unkown (not a stable version)
VERSION : 
	@echo "# This file was autogenerated by 'make'" >> $@.tmp
	@echo "DATE = "$(shell date +%F) >> $@.tmp
	@echo -n "VERS = " $(subst :,_, $(shell svnversion ..)) >> $@.tmp
	@echo $(shell (svn diff|grep -q '\.h\>\|\.cx*\>') >& /dev/null && echo -$$USER ) >> $@.tmp
	if ! diff $@ $@.tmp > /dev/null ; then \
		mv $@.tmp $@ ;  \
	fi
	rm -f $@.tmp
	cat $@

clean : 
	for dir in $(SUBDIRS); do \
	  $(MAKE) -C $$dir clean; \
	done

tags : TAGS
TAGS :
	etags --member -l c++ */*/*.{h,c,cxx,cc}	

data_subdirs : $(DATA_SUBDIRS) 
$(DATA_SUBDIRS) : 
	@echo "Populating $@/"
	@svn info data_subdirs/$@.tgz | grep '^Last Changed Rev:' 
	tar xzvvf data_subdirs/$@.tgz

conffiles : $(CONFFILES)
$(CONFFILES) : 
	@echo "Restoring $@"
	@svn info data_subdirs/$@ | grep '^Last Changed Rev:'
	cp data_subdirs/$@ $@
