#include "rootClass.h"
#include "comptonRunConstants.h"
#include "infoDAQ.C"
///Eventually, I should read in the scalar rate from the root tree for this run and create the corrB1* variables based on the aggregate rate in this category; The fit formula that was found from simulation will anyways be used by all runs. For now, I will simply read in this file generated by G 300 times for this run range used for comparison. 
Int_t corrDeadtime(Int_t runnum) {
  ifstream inRateCor0, inRateCor1;
  Bool_t debug = 0;
  Float_t corrB1H1L1_0=0.0,corrB1H1L0_0=0.0,corrB1H0L1_0=0.0,corrB1H0L0_0=0.0;//deadtime correction for given run
  Float_t corrB1H1L1_1=0.0,corrB1H1L0_1=0.0,corrB1H0L1_1=0.0,corrB1H0L0_1=0.0;//deadtime correction for given run
  Float_t runDum;
  if(retInfoDAQ ==0) retInfoDAQ = infoDAQ(runnum); ///needed acTrig for applying deadtime correction
  if(retInfoDAQ<0) {
    cout<<red<<"\nreturned error from infoDAQ.C hence exiting\n"<<normal<<endl;
    return -2;
  }

  if(acTrig==0) cout<<red<<"the trigger was found: "<<acTrig<<", still applying the deadtime correction for 2/3 trigger"<<normal<<endl;
  if(acTrig==2 || acTrig==0 || acTrig==1) {
    if(k2parDT) {
      cout<<blue<<"found the trigger to be "<<acTrig<<endl;
      cout<<"Applying 2 parameter Deadtime correction for 2/3 trigger"<<normal<<endl;
      inRateCor0.open(Form("%s/data/newdtcorr_2by3p0.dat",pPath));  //dtcorr_2by3p0.dat //dtcorr1by3_p0.dat 
      inRateCor1.open(Form("%s/data/newdtcorr_2by3p1.dat",pPath));///these files have all runs of run2
    } else {
      cout<<blue<<"Applying 1 parameter Deadtime correction for 2/3 trigger"<<normal<<endl;
      inRateCor0.open(Form("%s/data/dtcorr22.dat",pPath));
    }
  } else if(acTrig==3) {
    if(k2parDT) {
      cout<<blue<<"Applying 2 parameter Deadtime correction for 3/3 trigger"<<normal<<endl;
      inRateCor0.open(Form("%s/data/newdtcorr_3by3p0.dat",pPath));
      inRateCor1.open(Form("%s/data/newdtcorr_3by3p1.dat",pPath));
    } else {
      cout<<blue<<"Applying 1 parameter Deadtime correction for 3/3 trigger"<<normal<<endl;
      inRateCor0.open(Form("%s/data/dtcorr33.dat",pPath));
    }
  } else cout<<red<<"\nTrigger undetermined at "<<acTrig<<", hence DT correction not applied due to ambiguity\n"<<normal<<endl;
  if(acTrig==2 || acTrig==3 || acTrig==0) {
    if(inRateCor0.is_open()) {
      while(1) {
        inRateCor0>>runDum>>corrB1H1L1_0>>corrB1H1L0_0>>corrB1H0L1_0>>corrB1H0L0_0;
        if(debug) cout<<runDum<<"\t"<<corrB1H1L1_0<<"\t"<< corrB1H1L0_0<<"\t"<< corrB1H0L1_0<<"\t"<< corrB1H0L0_0<<endl;
        if(inRateCor0.eof()) {
          cout<<red<<"exiting the rate file because encountered the end of file"<<normal<<endl;///shouldn't happen
          inRateCor0.close();
          return -1;
        } else if(runDum == runnum) {
          cout<<blue<<"found the p0 correction factors for run "<<runnum<<" hence exiting"<<normal<<endl; 
          cout<<"correction factors:"<<corrB1H1L1_0<<"\t"<<corrB1H1L0_0<<"\t"<<corrB1H0L1_0<<"\t"<<corrB1H0L0_0<<"\n"<<endl;
          inRateCor0.close();
          break;
        }
      }
      if(k2parDT) {
        if(inRateCor1.is_open()) {
          while(1) {
            inRateCor1>>runDum>>corrB1H1L1_1>>corrB1H1L0_1>>corrB1H0L1_1>>corrB1H0L0_1;
            if(debug) cout<<runDum<<"\t"<<corrB1H1L1_1<<"\t"<< corrB1H1L0_1<<"\t"<< corrB1H0L1_1<<"\t"<< corrB1H0L0_1<<endl;
            if(inRateCor1.eof()) {
              cout<<red<<"exiting the rate file because encountered the end of file"<<normal<<endl;///shouldn't happen
              inRateCor1.close();
              return -1;
            } else if(runDum == runnum) {
              cout<<blue<<"found the p1 correction factors for run "<<runnum<<" hence exiting"<<normal<<endl;
              cout<<"correction factors:"<<corrB1H1L1_1<<"\t"<<corrB1H1L0_1<<"\t"<<corrB1H0L1_1<<"\t"<<corrB1H0L0_1<<"\n"<<endl;
              inRateCor1.close();
              break;
            }
          }
        } else cout<<red<<"\n***Alert: Could not open file for p1 DT correction factors\n"<<normal<<endl;
      }
    } else cout<<red<<"\n***Alert: Could not open file for p0 DT correction factors\n"<<normal<<endl;
  }
  /////Apply deadtime correction///////////////////
  if(corrB1H1L1_0==corrB1H1L0_0 || corrB1H0L1_0==corrB1H0L0_0) {
    cout<<red<<"\nthe correction factors for laser on/off is same for this run, hence something wrong\n"<<normal<<endl;
    cout<<"setting the deadtime correction factors to 1.0"<<endl;
    for (Int_t s =startStrip; s <endStrip; s++) {	
      c2B1H1L1[s] = 1.0 ;
      c2B1H1L0[s] = 1.0 ; 
      c2B1H0L1[s] = 1.0 ;
      c2B1H0L0[s] = 1.0 ;
    }
  }
  else if(k2parDT) {
    //cout<<"applying 2 parameter DT correction"<<endl;
    for (Int_t s =startStrip; s <endStrip; s++) {	
      c2B1H1L1[s] = (corrB1H1L1_0 + (s+1)*corrB1H1L1_1);
      c2B1H1L0[s] = (corrB1H1L0_0 + (s+1)*corrB1H1L0_1); 
      c2B1H0L1[s] = (corrB1H0L1_0 + (s+1)*corrB1H0L1_1);
      c2B1H0L0[s] = (corrB1H0L0_0 + (s+1)*corrB1H0L0_1);
    }
  } else {
    //cout<<"applying 1 parameter DT correction"<<endl;
    for (Int_t s =startStrip; s <endStrip; s++) {	
      c2B1H1L1[s] = corrB1H1L1_0 ;
      c2B1H1L0[s] = corrB1H1L0_0 ; 
      c2B1H0L1[s] = corrB1H0L1_0 ;
      c2B1H0L0[s] = corrB1H0L0_0 ;
    }
  }
  return 1;
}
//the corr* variables depend on the aggregate rate at a time, unaffected by individual strip rate
/////////////////////////////////////////////////

