#!/bin/bash
umask 002

#  Do a little gymnastics to figure out which installed
#  analyzer version is being called.
initialDir=`pwd`
cd `dirname $0`
scriptPath=`pwd`
cd $initialDir

export QWSCRATCH=/group/qweak/QwAnalysis/common/QwScratch
export QWANALYSIS=`echo $scriptPath | sed 's/Extensions\/Auger\/batchman//'`
. $QWANALYSIS/SetupFiles/SET_ME_UP.bash >& /dev/null

$QWANALYSIS/Extensions/Auger/batchman/qwbmodsub.pl --job-maxmemory 3000 \
    --post-run $QWANALYSIS/Extensions/Regression/QwBeamModulation/scripts/bash/bmod_r1p5a_batch.bash  \
    --post-run $QWANALYSIS/Extensions/Regression/QwBeamModulation/Slug/run_makeslug_mps_r1p5a \
    --rootfile-stem QwPass5_ $@

