#!/bin/bash
umask 002

export QWSCRATCH=/group/qweak/QwAnalysis/common/QwScratch
export QWANALYSIS=/group/qweak/QwAnalysis/Linux_CentOS5.3-x86_64/QwAnalysis_2.00
. $QWANALYSIS/SetupFiles/SET_ME_UP.bash >& /dev/null

echo "### "
echo "### NOTE:  By default, the ROOT files will not be saved by"
echo "###        jobs submitted with this script, due to issues"
echo "###        copying the files to tape."
echo "### "
echo "###        If for a limited number of runs we need to have"
echo "###        the rootfiles saved, add the following option to the"
echo "###        'official_qwbatchsub' command line."
echo "### "
echo "###        '--rootfile-output mss:/mss/hallc/qweak/rootfiles/pass3'"
echo "### "


# --post-run $QWANALYSIS/Extensions/Macros/Parity/beamModulation/bmod_optics  \
# --post-run /home/pking/Qweak/data_tracker/autoanalyzer/prompt_summary.sh \

$QWANALYSIS/Extensions/Auger/batchman/qwbatchsub.pl \
    --post-runlet $QWANALYSIS/Extensions/Auger/batchman/regression_run2pass1.sh \
    --rootfile-stem QwPass1_ \
    --rootfile-output file:/volatile/hallc/qweak/QwAnalysis/run2/rootfiles \
    --options "--config official_run2pass1.conf" $@
