#!/bin/bash
umask 002

export QWSCRATCH=/group/qweak/QwAnalysis/common/QwScratch
export QWANALYSIS=/group/qweak/QwAnalysis/Linux_CentOS5.3-x86_64/QwAnalysis_3.04
. $QWANALYSIS/SetupFiles/SET_ME_UP.bash >& /dev/null

echo "### "
echo "### NOTE:  By default, the ROOT files will not be saved by"
echo "###        jobs submitted with this script, due to issues"
echo "###        copying the files to tape."
echo "### "
echo "###        If for a limited number of runs we need to have"
echo "###        the rootfiles saved, add the following option to the"
echo "###        'official_qwbatchsub' command line."
echo "### "
echo "###        '--rootfile-output mss:/mss/hallc/qweak/rootfiles/pass3'"
echo "### "


$QWANALYSIS/Extensions/Auger/batchman/qwbatchsub.pl --max-files-per-job 6 \
    --post-run $QWANALYSIS/Extensions/Regression/QwBeamModulation/scripts/bash/bmod_r1p5_batch.bash  \
    --post-run $QWANALYSIS/Extensions/Regression/QwBeamModulation/Slug/run_makeslug_mps \
    --post-runlet $QWANALYSIS/Extensions/Auger/batchman/regression_run1pass5.sh \
    --post-runlet $QWANALYSIS/Extensions/Macros/Parity/SlugPlots/run1pass5/run_makesluglet \
    --post-runlet $QWANALYSIS/Extensions/Auger/batchman/regression_run1pass5_bmod.sh \
    --rootfile-stem QwPass5_ \
    --end-script $QWANALYSIS/Extensions/Auger/batchman/outputstage_r1p5 \
    --rootfile-output null \
    --options "--config official_run1pass5.conf --QwDatabase.dbname qw_run1_pass5" $@

