#!/bin/bash
umask 002

export QWSCRATCH=/group/qweak/QwAnalysis/common/QwScratch
export QWANALYSIS=/group/qweak/QwAnalysis/Linux_CentOS5.3-x86_64/QwAnalysis_1.09
. $QWANALYSIS/SetupFiles/SET_ME_UP.bash >& /dev/null

echo "### "
echo "### NOTE:  By default, the ROOT files will not be saved by"
echo "###        jobs submitted with this script, due to issues"
echo "###        copying the files to tape."
echo "### "
echo "###        If for a limited number of runs we need to have"
echo "###        the rootfiles saved, add the following option to the"
echo "###        'official_qwbatchsub' command line."
echo "### "
echo "###        '--rootfile-output mss:/mss/hallc/qweak/rootfiles/pass3'"
echo "### "


$QWANALYSIS/Extensions/Auger/batchman/qwbatchsub.pl --post-runlet $QWANALYSIS/Extensions/Auger/batchman/regression.sh --rootfile-stem QwPass3_ --rootfile-output none --options "--config official_pass3.conf" $@
