#!/bin/bash
umask 002

export QWSCRATCH=/group/qweak/QwAnalysis/common/QwScratch
export QWANALYSIS=/group/qweak/pking/local_devel/ifarml4/QwAnalysis_new
. $QWANALYSIS/SetupFiles/SET_ME_UP.bash >& /dev/null

echo "### "
echo "### NOTE:  By default, the ROOT files will not be saved by"
echo "###        jobs submitted with this script, due to issues"
echo "###        copying the files to tape."
echo "### "
echo "###        If for a limited number of runs we need to have"
echo "###        the rootfiles saved, add the following option to the"
echo "###        'official_qwbatchsub' command line."
echo "### "
echo "###        '--rootfile-output mss:/mss/hallc/qweak/rootfiles/pass3'"
echo "### "


$QWANALYSIS/Extensions/Auger/batchman/qwbatchsub.pl --post-runlet $QWANALYSIS/Extensions/Auger/batchman/regression_run1pass5beta.sh --rootfile-stem QwPass5beta_ --rootfile-output file:/volatile/hallc/qweak/QwAnalysis/run1/rootfiles --options "--config official_run1pass5beta.conf" $@
