#!/bin/bash
run=$1
seg=$2

if [ $# -ne 2 ] ; then
   echo The volatile stager wrapper script needs run_number and segment_number
   exit
fi

PathToVolatile="/volatile/hallc/qweak/QwAnalysis/run1"

SendToSilo="/u/group/qweak/QwAnalysis/common/perl/send_rootfiles_to_silo.pl --regex-pattern .+[^0-9\]${run}\[^0-9\].+ --age 1"

oldPath=`pwd`
cd $PathToVolatile
$SendToSilo pass5/Slugs          ./pass5_slugs
$SendToSilo pass5/lrb_rootfiles  ./pass5_lrb_rootfiles
$SendToSilo pass5/bmod_mpsslug   ./pass5_bmod_mpsslug
$SendToSilo pass5/bmod_rootfiles ./pass5_bmod_rootfiles/set1
$SendToSilo pass5/bmod_rootfiles ./pass5_bmod_rootfiles/set2
$SendToSilo pass5/bmod_rootfiles ./pass5_bmod_rootfiles/set3
$SendToSilo pass5/bmod_rootfiles ./pass5_bmod_rootfiles/set4 
cd $oldPath