#!/bin/bash
umask 002

#  Do a little gymnastics to figure out which installed
#  analyzer version is being called.
initialDir=`pwd`
cd `dirname $0`
scriptPath=`pwd`
cd $initialDir

export QWSCRATCH=/group/qweak/QwAnalysis/common/QwScratch
export QWANALYSIS=`echo $scriptPath | sed 's/Extensions\/Auger\/batchman//'`
. $QWANALYSIS/SetupFiles/SET_ME_UP.bash >& /dev/null

$QWANALYSIS/Extensions/Auger/batchman/qwbatchsub.pl --max-files-per-job 5 \
    --job-maxmemory 3000 \
    --rootfile-stem QwPass5b_tgtboiling_ \
    --rootfile-output file:/volatile/hallc/qweak/QwAnalysis/target_studies/rootfiles \
    --options "--config official_run1pass5.conf --QwDatabase.dbname qw_test_20120720" $@

###     --end-script $QWANALYSIS/Extensions/Auger/batchman/outputstage_r1p5b \

