#!/bin/bash


slug_num=$1
#dir=/work/hallc/qweak/rakithab/QwAnalysis_trunk/Extensions/Macros/Parity/SlugPlots/run1pass4/
#this is the source of regressed root files
SRC="/volatile/hallc/qweak/QwAnalysis/run1/pass4bregression/lrb_rootfiles"
#DST="/volatile/hallc/qweak/rakithab/run1pass4/slugs"
DST="/volatile/hallc/qweak/QwAnalysis/run1/pass4bslugs/slugs"
DST_Dbug="/volatile/hallc/qweak/QwAnalysis/run1/pass4bslugs/out_files"
#DST_Dbug="/volatile/hallc/qweak/rakithab/run1pass4/out_files"
###############
#
# first make links
#
#./collect_lrb_links std
#./collect_lrb_links 5+1
#./collect_lrb_links set3
#./collect_lrb_links set4
#./collect_lrb_links set5
#./collect_lrb_links set6
#
###############

###############
#
# for testing purposes
#
#argument1="MakeSlug_lrb.C+(\"test.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"slugs/test.root\",\"std\")"
#root -q -b -l ${argument1} 
#root -q -b -l 'MakeSlug_lrb.C+("test.txt","leaflist_run1pass4_lrb_reg.txt","slugs/test.root","std")'
#
###############



################
#
# check that all runlets exist for all slugs
#
# taking care of this when making the goodrun lists
#
################

 

#need a check to see all the root files(regressed and unregressed) are available for all the runs in the slug file list before running the script




argument="MakeSlug.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_unreg.txt\",\"${DST}/slug${slug_num}.root\")"
argument1="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_std.root\",\"std\")"
argument2="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_5+1.root\",\"5+1\")"
argument3="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set3.root\",\"set3\")"
argument4="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set4.root\",\"set4\")"
argument5="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set5.root\",\"set5\")"
argument6="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set6.root\",\"set6\")"
argument7="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set7.root\",\"set7\")"
argument8="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set8.root\",\"set8\")"
argument9="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set9.root\",\"set9\")"
argument10="MakeSlug_lrb.C+(\"slug${slug_num}_goodruns_list.txt\",\"leaflist_run1pass4_lrb_reg.txt\",\"${DST}/slug${slug_num}_lrb_set10.root\",\"set10\")"

 




root -n -q -b -l ${argument} >${DST_Dbug}/slug${slug_num}.out
root -n -q -b -l ${argument1} >${DST_Dbug}/slug${slug_num}_lrb_std.out
root -n -q -b -l ${argument2} >${DST_Dbug}/slug${slug_num}_lrb_5+1.out
root -n -q -b -l ${argument3} >${DST_Dbug}/slug${slug_num}_lrb_set3.out
root -n -q -b -l ${argument4} >${DST_Dbug}/slug${slug_num}_lrb_set4.out 
root -n -q -b -l ${argument5} >${DST_Dbug}/slug${slug_num}_lrb_set5.out
root -n -q -b -l ${argument6} >${DST_Dbug}/slug${slug_num}_lrb_set6.out
root -n -q -b -l ${argument7} >${DST_Dbug}/slug${slug_num}_lrb_set7.out
root -n -q -b -l ${argument8} >${DST_Dbug}/slug${slug_num}_lrb_set8.out
root -n -q -b -l ${argument9} >${DST_Dbug}/slug${slug_num}_lrb_set9.out
root -n -q -b -l ${argument10} >${DST_Dbug}/slug${slug_num}_lrb_set10.out




